# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: action-zip
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq build.zip -d build
    
  
